###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "satinderpal",
  "name": "satinderpal",
  "password": "yuvraj123"
}



### send the get request
GET http://localhost:3003/api/users 
